// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "../extra/themes/default/lv_theme_default.h"
///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_ImgButton1;
lv_obj_t *ui_ImgButton2;
lv_obj_t *ui_ImgButton3;
lv_obj_t *ui_ImgButton4;
lv_obj_t *ui_ImgButton5;
lv_obj_t *ui_ImgButton6;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
	ui_Screen1 = lv_obj_create(NULL);
	lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

	ui_Panel1 = lv_obj_create(ui_Screen1);
	lv_obj_set_width( ui_Panel1, 240);
	lv_obj_set_height( ui_Panel1, 240);
	lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
	lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

	ui_ImgButton1 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_camera_png, NULL);
	lv_obj_set_height( ui_ImgButton1, 92);
	lv_obj_set_width( ui_ImgButton1, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_x( ui_ImgButton1, -27 );
	lv_obj_set_y( ui_ImgButton1, 60 );
	lv_obj_set_align( ui_ImgButton1, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton1,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

	ui_ImgButton2 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_image_png, NULL);
	lv_obj_set_height( ui_ImgButton2, 92);
	lv_obj_set_width( ui_ImgButton2, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_x( ui_ImgButton2, -99 );
	lv_obj_set_y( ui_ImgButton2, -18 );
	lv_obj_set_align( ui_ImgButton2, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton2,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

	ui_ImgButton3 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_png, NULL);
	lv_obj_set_height( ui_ImgButton3, 92);
	lv_obj_set_width( ui_ImgButton3, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_x( ui_ImgButton3, 0 );
	lv_obj_set_y( ui_ImgButton3, 1 );
	lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton3,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

	ui_ImgButton4 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sd_png, NULL);
	lv_obj_set_height( ui_ImgButton4, 92);
	lv_obj_set_width( ui_ImgButton4, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_align( ui_ImgButton4, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton4,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

	ui_ImgButton5 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_png, NULL);
	lv_obj_set_height( ui_ImgButton5, 92);
	lv_obj_set_width( ui_ImgButton5, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_x( ui_ImgButton5, 46 );
	lv_obj_set_y( ui_ImgButton5, 51 );
	lv_obj_set_align( ui_ImgButton5, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton5,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

	ui_ImgButton6 = lv_imgbtn_create(ui_Panel1);
	lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_key_png, NULL);
	lv_obj_set_height( ui_ImgButton6, 92);
	lv_obj_set_width( ui_ImgButton6, LV_SIZE_CONTENT);  /// 1
	lv_obj_set_x( ui_ImgButton6, -80 );
	lv_obj_set_y( ui_ImgButton6, 48 );
	lv_obj_set_align( ui_ImgButton6, LV_ALIGN_CENTER );
	lv_obj_set_flex_flow(ui_ImgButton6,LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(ui_ImgButton6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

}

void ui_init( void )
{
	lv_disp_t *dispp = lv_disp_get_default();
	lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
	lv_disp_set_theme(dispp, theme);
	ui_Screen1_screen_init();
	ui____initial_actions0 = lv_obj_create(NULL);
	lv_disp_load_scr( ui_Screen1);
}
