// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel2;
void ui_event_ImgButton1(lv_event_t *e);
lv_obj_t *ui_ImgButton1;
void ui_event_ImgButton2(lv_event_t *e);
lv_obj_t *ui_ImgButton2;
void ui_event_ImgButton3(lv_event_t *e);
lv_obj_t *ui_ImgButton3;
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Calendar1;
void ui_event_ImgButton6(lv_event_t *e);
lv_obj_t *ui_ImgButton6;
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Chart2;
void ui_event_ImgButton5(lv_event_t *e);
lv_obj_t *ui_ImgButton5;
lv_obj_t *ui_Screen4;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Checkbox1;
lv_obj_t *ui_Roller1;
lv_obj_t *ui_Switch1;
lv_obj_t *ui_Spinner1;
void ui_event_ImgButton4(lv_event_t *e);
lv_obj_t *ui_ImgButton4;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ImgButton1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}
void ui_event_ImgButton2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}
void ui_event_ImgButton3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen4, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}
void ui_event_ImgButton6(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}
void ui_event_ImgButton5(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}
void ui_event_ImgButton4(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 240);
    lv_obj_set_height(ui_Panel2, 240);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_ImgButton1 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_takepic_png, NULL);
    lv_obj_set_height(ui_ImgButton1, 96);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_ImgButton2 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_image_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 96);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 96);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
}
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Screen2);
    lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 240);
    lv_obj_set_height(ui_Calendar1, 180);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_BOTTOM_MID);

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_height(ui_ImgButton6, 96);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ImgButton6, -1);
    lv_obj_set_y(ui_ImgButton6, -79);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
}
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Chart2 = lv_chart_create(ui_Screen3);
    lv_obj_set_width(ui_Chart2, 240);
    lv_obj_set_height(ui_Chart2, 143);
    lv_obj_set_x(ui_Chart2, 2);
    lv_obj_set_y(ui_Chart2, 68);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_series_t *ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xEB798D), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = {0, 50, 20, 40, 10, 80, 40, 20, 70, 0};
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    ui_ImgButton5 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_height(ui_ImgButton5, 96);
    lv_obj_set_width(ui_ImgButton5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ImgButton5, 0);
    lv_obj_set_y(ui_ImgButton5, -80);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
}
void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, 54);
    lv_obj_set_y(ui_Label2, -21);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "hello world");

    ui_Checkbox1 = lv_checkbox_create(ui_Screen4);
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Checkbox1, 52);
    lv_obj_set_y(ui_Checkbox1, 12);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags

    ui_Roller1 = lv_roller_create(ui_Screen4);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 153);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Roller1, -71);
    lv_obj_set_y(ui_Roller1, 40);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 47);
    lv_obj_set_y(ui_Switch1, 49);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Spinner1 = lv_spinner_create(ui_Screen4, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 64);
    lv_obj_set_height(ui_Spinner1, 62);
    lv_obj_set_x(ui_Spinner1, -79);
    lv_obj_set_y(ui_Spinner1, -80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE); /// Flags

    ui_ImgButton4 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_height(ui_ImgButton4, lv_pct(40));
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ImgButton4, -2);
    lv_obj_set_y(ui_ImgButton4, -80);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
}

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
