// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_ImgButton1;
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_ImgButton3;
extern lv_obj_t *ui_ImgButton4;
extern lv_obj_t *ui_ImgButton5;
extern lv_obj_t *ui_ImgButton6;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_camera_png);   // assets\camera.png
LV_IMG_DECLARE( ui_img_image_png);   // assets\image.png
LV_IMG_DECLARE( ui_img_weather_png);   // assets\weather.png
LV_IMG_DECLARE( ui_img_sd_png);   // assets\sd.png
LV_IMG_DECLARE( ui_img_set_png);   // assets\set.png
LV_IMG_DECLARE( ui_img_key_png);   // assets\key.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
